name: shopfly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  #Enabling connecting to multiple Firebase apps
  firebase_core: ^3.12.0
  #Flutter plugin for discovering the state of the network
  connectivity_plus: ^6.1.3
  #Configure any flutter application with global variables
  flutter_dotenv: ^5.2.1
  #Adapting screen and font size
  flutter_screenutil: ^5.9.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  #Updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.14.3
  #Lint rules for Dart and Flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
      - .env.dev
      - .env.prod
      - assets/images/core/
